### ISSUE TITLE
Are you still active? 

### ISSUE THREAD

**Issue by johnsonthedev** [mehwww/vue-sticky-directive#1]
Hi, 

last update is a while and I wonder if you still using it ? I found a few issues and have a couple of questions regarding this package. 

Are you still with Vue.js an plan to support this package in future? If I understand your code I could help.

Cheers!

**Comment by mehwww** [comment]
I'm alive and I'm using this lib in production pretty well and have not any problem yet 😊so there is no update long time, if you have questions any PR or issues are welcome

**Comment by maksnester** [comment]
@mehwww why in your package.json specified another repo? Not this one?

**Comment by mehwww** [comment]
> @mehwww why in your package.json specified another repo? Not this one?

😊 my mistake sry
