### ISSUE TITLE
Ran into "Cannot read property 'removeChild' of null" error

### ISSUE THREAD

**Issue by jingzhaoo** [mehwww/vue-sticky-directive#14]
Really nice and useful module! Just ran into the "Cannot read property 'removeChild' of null" error. It does not seem to affect any actual functionality. But still, it is better that if we can remove it. According to the log, it seems to be from here:

```  }, {
    key: 'resetElement',
    value: function resetElement() {
      var _this3 = this;

      ['position', 'top', 'bottom', 'left', 'width', 'zIndex'].forEach(function (attr) {
        _this3.el.style.removeProperty(attr);
      });
      this.placeholderEl.parentNode.removeChild(this.placeholderEl);
    }```

Not sure why, but `this.placeholderEl.parentNode` may be `null` in my case.

**Comment by progand** [comment]
@mehwww Can you make release with this fix? Latest release `0.0.7` doesn't include it

**Comment by mehwww** [comment]
Sorry forgot to push it, it's already published to npm

**Comment by chvs** [comment]
the same error occurred however after updating from version 0.0.6 to the last, it stopped fixing at the top, I had to roll back the version :(
by the way I use it with Nuxt.js, maybe this is the problem
