### ISSUE TITLE
Documentation for offset is confusing

### ISSUE THREAD

**Issue by marky291** [mehwww/vue-sticky-directive#19]
I am kinda new to this vue thing, the instructions in the documentation are unclear on offset settings.

**Comment by bigoper** [comment]
True :)

Look at the example file, you'll see how to do it.
- you need to declare relevant data
``` offset: {top: 10, bottom: 30},```

```js
/* eslint-disable */
import Sticky from '../../src/sticky.js'

Vue.directive('Sticky', Sticky)

new Vue({
  el: document.querySelector('.app'),
  template: '#app-template',
  data: {
    offset: {top: 10, bottom: 30},
    stickyEnabled: true,
  },
  methods: {
    onStick(data) {
      console.log(data);
    }
  }
})
```

### NOTE
- yet, it's still not working. I can't get the offset to work.

**Comment by marky291** [comment]
@bigoper thanks for the reply.

@mehwww please assist.

**Comment by AMoreaux** [comment]
The code below worked for me.

The `sticky-offset` attribute is a string which is a reference to the property offset in the data object.

```vue
<template>
  <div class="app-wrapper">
    <navigation v-sticky sticky-offset="offset" sticky-side="top" />
    <slot />
  </div><!-- /.app-wrapper -->
</template>

<script>

import Navigation from '@/components/nav'

export default {
  name: 'DefaultLayout',
  data() {
    return{
      offset: {top: 10, bottom: 30},
    }
  },
  components: {
    Navigation
  },
}
</script>
```

**Comment by SacDin** [comment]
Strange that it works only with assigning data property but does not work when object provided inline like `:sticky-offset="{top: 30}"`

**Comment by bigoper** [comment]
@AMoreaux 
### You've mentioned a 'string' but your offset is an 'object'
- ```offset: {top: 10, bottom: 30}``` and not ```offset: "{top: 10, bottom: 30}"```

### sticky-container
- Your example is missing it. there's no need for it? or in this case its within a higher component?

And it still won't work.

Thanks again!

**Comment by AMoreaux** [comment]
* I did not put `sticky-container` anywhere.

* If you look in the library code  [here](https://github.com/mehwww/vue-sticky-directive/blob/master/src/sticky.js#L236). We can see that we get the string of an attribute and then we get the object of the same name declare in the data of the component. This is why you have to declare the attribute to offset as a static prop.

```js
const offset = this.getAttribute('sticky-offset')
```
```js
getAttribute (name) {
    const expr = this.el.getAttribute(name) // expr: 'offset'
    if (expr) {
      return this.vm[expr] || expr // same as: this.data['offset']
    } else {
      return undefined
    }
  }
```
That's why you have to declare the `sticky-offset` attribute in html as static prop. @SacDin

**Comment by SacDin** [comment]
@AMoreaux Understood, thank you.
You may close this issue now as per my opinion. It is all clear now.

**Comment by marky291** [comment]
Should be documented as such, was what I was aiming for. thanks.

**Comment by wrabit** [comment]
Completely confusing docs.

**Comment by mehwww** [comment]
Sorry for the poor docs after all English is not my first language 😅. I have just published 0.0.9 which support both variable name attribute or a js expression, please refer to [this](https://github.com/mehwww/vue-sticky-directive/commit/2529afef791142ec61532acaec78aa3305b95229) commit.
If you have any problem about using, just check the example or the source code, it's not very complex 😘.

**Comment by lifenautjoe** [comment]
Still confused over here, adding ```:sticky-offset="{top: 30, bottom: 20}"``` does nothing. It simply sticks the element but with no top nor bottom offset.

**Comment by lifenautjoe** [comment]
I ended up adding a top offset myself with css as anything else didn't work..

```
        .top-sticky {
            .ok-desktop-user-profile-sidebar {
                position: relative;
                top: 95px !important;
            }
        }
```

**Comment by tbredin** [comment]
Very confusing documentation. That `sticky-offset` is a string that looks for a matching data property of the same name is not clear at all.

From the docs, I too would have expected `:sticky-offset="{top: 30, bottom: 20}"` to work.
