### ISSUE TITLE
Add browser field in package.json

### ISSUE THREAD

**Issue by deraw** [mehwww/vue-sticky-directive#28]
Hi,

In v0.0.10, the `module` field was added to `package.json`, but there is [a bug in webpack](https://github.com/webpack/webpack/issues/5756), `module` gets prioritised over `main`

This is an issue because we need ES5 for IE
[This comment](https://github.com/webpack/webpack/issues/5756#issuecomment-504919312) suggets to add  the `browser` field to `package.json` to fix the issue, I think it would be nice to do the same!

Thanks

**Comment by mehwww** [comment]
Sure, PR is welcome 😄
