### ISSUE TITLE
How to prevent placeholder behavior?

### ISSUE THREAD

**Issue by wpatter6** [mehwww/vue-sticky-directive#3]
Hi, I am having this strange behavior where when I mark an element as v-sticky, it will not be visible on the page until I start scrolling, with what appears to be a placeholder element in its place.  When scrolling starts, the sticky element becomes visible.  Before scrolling it seems to have a 'left' of some large number which pushes it off the page.

I have been able to override this behavior with the css `left: auto !important` which seems to work OK but I was wondering if there was a less hacky way to do what I'm trying to do.

Thanks!

Edit: I believe this is happening because the sticky element lives on a slider, which is offset to be off the right side of the page until it is triggered to become visible, then it is moved into the visible area.  However, when that happens the element doesn't get it's left style updated so it is not visible.  I'm guessing there's not anything that can be done about that, though if I could suggest an option to set left:auto instead of being calculated, that might be a better solution than what I'm doing now.

**Comment by mehwww** [comment]
Hi, sorry I'm not sure what your issue is, can you have a reproduce jsfiddle or something else plz ?

**Comment by wpatter6** [comment]
Ok here is a sandbox that displays this behavior: https://codesandbox.io/s/r4km3483zn

See the slider.vue component for the code, with comments on lines 57 and 127.  

Basically, if the sticky directive is used on an element that moves, the recalculation of the element's position is not performed so it is not moved along with the parent.  Using 'left: auto' works in most browsers, but IOS does not seem to work well with this property value.  

I'm guessing triggering a window resize or scroll event would cause it to behave better, but I'd consider this to be another hack, and getting it to animate properly would be a pain.

**Comment by mehwww** [comment]
Emmm sry this lib is not design to such a complex situation, you may fork this repo and change it to meet your demand, also I will be appreciate if you'd like to make a PR. :blush:
