### ISSUE TITLE
Use of eval

### ISSUE THREAD

**Issue by gmoneh** [mehwww/vue-sticky-directive#31]
The use of eval within the code of the sticky directive causes a non-fatal warning when building through roll-up. 
node_modules\vue-sticky-directive\src\sticky.js
261:       } else {
262:         try {
263:           result = eval(`(${expr})`);
                        ^
264:         } catch (error) {
265:           result = expr;

Is there a way to accomplish this without using eval, so we'd be able to get a clean build?

Thanks!

**Comment by mehwww** [comment]
You can use `rollup --silent` to mute console output.
