### ISSUE TITLE
Offset and side don't appear to do anything

### ISSUE THREAD

**Issue by wpatter6** [mehwww/vue-sticky-directive#4]
Hello,

I found another issue hopefully you can help me with, it does not appear to have any effect setting the offset and side values of the v-sticky per the example.  See this sandbox for example: https://codesandbox.io/s/4xv0561vx7 -- perhaps I am doing this incorrectly?

Thank you.

**Comment by mehwww** [comment]
I modify your box make it work [https://codesandbox.io/s/8zjxy5mjl](https://codesandbox.io/s/8zjxy5mjl), notice that it's `sticky-offset` not `:sticky-offset`, and side value `both` and `bottom` will work if the sticky element is in the middle position of its sticky container.
