### ISSUE TITLE
Minor issue activating stickyness

### ISSUE THREAD

**Issue by mbalandis** [mehwww/vue-sticky-directive#9]
Hi,

This directive works really well so thank you very much for creating it.
I have a minor issue and wonder if it can be fixed on your end. Not sure if you are experiencing this as well but...

Basically if I have a long page vertically, for example, a table, and want to stick a div to bottom, if the div is too far down to the bottom it won't show up until i scroll the window up or down a pixel.

Is it a way to make it stick immediately? 

Hope that makes sense. If not let me know.

**Comment by mehwww** [comment]
You may try to dispatch a resize event manually like `window.dispatchEvent(new Event('resize'))` in your component's `mounted` lifecycle method, it will force this lib check should the div be sticky, just like when you scroll your screen.

**Comment by mbalandis** [comment]
That is exactly the method I needed, I tried with window.scrollTo(), etc, with no luck. I did it not do that in mounted(), but did the method on the play event. When I try to do on click I have to do it twice. But this method did provide a decent workaround :) Regardless it is still a workaround and may or not work on other circumstances.
Thank you for the help!
